chore: update devfiles

diff --git a/.github/workflows/cd-maven-jreleaser-library.yml b/.github/workflows/cd-maven-jreleaser-library.yml
--- a/.github/workflows/cd-maven-jreleaser-library.yml
+++ b/.github/workflows/cd-maven-jreleaser-library.yml
@@ -2,7 +2,7 @@
 # Continuous delivery with JReleaser
 # Why not? maven, it creates a nice GitHub release
 
-name: Continuous Deployment to Maven Central Repository
+name: Continuous Deploy Maven Repository
 on:
   # Trigger on button click
   workflow_dispatch:
@@ -10,12 +10,14 @@ on:
   push:
     paths:
       - 'pom.xml'
+      - '**.java'
     branches:
       - 'main'
 jobs:
   publish:
     # Slim is one CPU vs 4 for the standard ubuntu-latest
     # Price is at the core by minutes
+    # We need to install java, and it's slower so it's maybe not a gain
     runs-on: ubuntu-slim
     steps:
 
@@ -37,25 +39,9 @@ jobs:
           java-version: '17'
           distribution: 'temurin'
 
+      # Ref
+      # https://jreleaser.org/guide/latest/examples/maven/maven-central.html#_maven
       - name: Publish package
-        run: |
-
-          set -TCEeuo pipefail
-
-          echo "Check config"
-          if ! CHECK_CONFIG=$(./mvnw --batch-mode -s .github/cd-maven-settings.xml --quiet jreleaser:config); then
-            echo "Error while checking the config"
-            echo "$CHECK_CONFIG"
-            exit 1
-          fi
-
-          echo "Stage Artifacts"
-          ./mvnw --batch-mode -s .github/cd-maven-settings.xml --quiet -Ppublication
-
-          # Deploy snapshot or release
-          echo "Deploy snapshot or release"
-          ./mvnw --batch-mode -s .github/cd-maven-settings.xml jreleaser:deploy
-
         env:
           # https://central.sonatype.com/usertoken
           JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
@@ -67,3 +53,28 @@ jobs:
           JRELEASER_GPG_PASSPHRASE: ${{ secrets.GPG_SOFTWARE_SIGNING_PASSPHRASE }}
           # GitHub Token for release creation
           JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+
+          set -TCEeuo pipefail
+
+          echo "Test"
+          ./mvnw --batch-mode -s .github/cd-maven-settings.xml test
+
+          echo "Check config"
+          if ! CHECK_CONFIG=$(./mvnw --batch-mode -s .github/cd-maven-settings.xml --quiet jreleaser:config); then
+            echo "Error while checking the config"
+            echo "$CHECK_CONFIG"
+            exit 1
+          fi
+
+          echo "Stage Artifacts"
+          # The publication profile should be in the parent or the pom
+          # as seen here: https://jreleaser.org/guide/latest/examples/maven/maven-central.html#_maven
+          # and here: https://jreleaser.org/guide/latest/examples/maven/staging-artifacts.html
+          # It will attach the maven-javadoc-plugin and maven-source-plugin
+          ./mvnw --batch-mode -s .github/cd-maven-settings.xml --quiet -Ppublication
+
+          # Deploy snapshot or release
+          # https://jreleaser.org/guide/latest/tools/jreleaser-maven.html#_jreleaserdeploy
+          echo "Deploy snapshot or release"
+          ./mvnw --batch-mode -s .github/cd-maven-settings.xml -DskipTests jreleaser:deploy
